<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-23 at 16:08:58.
 */
class CoupTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Coup
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Coup;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Coup::evaluer
     * @todo   Implement testEvaluer().
     */
    public function testEvaluer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coup::estUnDraw
     * @todo   Implement testEstUnDraw().
     */
    public function testEstUnDraw() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coup::getFigureJoueur1
     * @todo   Implement testGetFigureJoueur1().
     */
    public function testGetFigureJoueur1() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coup::getFigureJoueur2
     * @todo   Implement testGetFigureJoueur2().
     */
    public function testGetFigureJoueur2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Coup::getJoueurGagnantCoup
     * @todo   Implement testGetJoueurGagnantCoup().
     */
    public function testGetJoueurGagnantCoup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
