<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-23 at 16:02:12.
 */
class MancheTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Manche
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Manche;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Manche::ajoutCoup
     * @todo   Implement testAjoutCoup().
     */
    public function testAjoutCoup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Manche::verifFinManche
     * @todo   Implement testVerifFinManche().
     */
    public function testVerifFinManche() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Manche::getJoueurGagnantManche
     * @todo   Implement testGetJoueurGagnantManche().
     */
    public function testGetJoueurGagnantManche() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
